### ISSUE TITLE
Проверить ДЗ

### ISSUE THREAD

**Issue by aselnigmatullina** [aselnigmatullina/TopPosts#1]

**Comment by coursar** [comment]
Хитро, конечно, что в минус нельзя уйти.

Если бы было можно, тогда бы ваша логика была нарушена (т.е. если у всех постов был бы отрицательный рейтинг, то новый пост с нулевым рейтингом через `push` добавлялся бы в конец)

**Comment by aselnigmatullina** [comment]
@coursar, Добрый вечер) 
Я изменила код, сделала как по видео про DOM)

**Comment by coursar** [comment]
Сейчас стало не совсем правильно: нужно сортировать ещё при добавлении, иначе получится вот так (0 лайков ниже отрицательных):
<img width="971" alt="Снимок экрана 2019-11-22 в 16 01 10" src="https://user-images.githubusercontent.com/3601892/69428065-6bbff900-0d41-11ea-8127-1cbf43fb3808.png">

**Comment by aselnigmatullina** [comment]
@coursar , изменила код) Лайки работают верно)
